version: 2.0
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: quay.io/haskell_works/stack-build-minimal:18.04

    steps:
      - checkout

      - run: git fetch --unshallow || true

      - run:
          name: Copying scripts
          command: |
            mkdir -p ~/.local/bin
            cp ./scripts/* ~/.local/bin

      - run:
          name: Query resolver & ghc version
          command: |
            resolver > resolver.version
            ghc-version $(cat resolver.version) >  ghc.version

      - restore_cache:
          key: cache--librdkafka-{{ checksum "scripts/build-librdkafka.sh" }}
      - run:
          name: Build librdkafka
          command: ./scripts/build-librdkafka.sh
      - save_cache:
          key: cache--librdkafka-{{ checksum "scripts/build-librdkafka.sh" }}
          paths: ~/project/.librdkafka

      - restore_cache:
          keys:
                - stack--{{ checksum "ghc.version" }}--{{ .Environment.CACHE_VERSION }}--{{ checksum "resolver.version" }}--{{ checksum "package.yaml" }}--{{ checksum "stack.yaml" }}
                - stack--{{ checksum "ghc.version" }}--{{ .Environment.CACHE_VERSION }}--{{ checksum "resolver.version" }}--{{ checksum "package.yaml" }}
                - stack--{{ checksum "ghc.version" }}--{{ .Environment.CACHE_VERSION }}--{{ checksum "resolver.version" }}
                - stack--{{ checksum "ghc.version" }}--only

      - run: stack setup

      - save_cache:
          key:    stack--{{ checksum "ghc.version" }}--only
          paths:  [~/.stack, ~/project/.stack-work]

      - run: |
          stack build bytestring
          stack build text
          stack build clock
          stack build mtl
          stack build network
          stack build parallel
          stack build Cabal
          stack build HUnit
          stack build --test --no-run-tests --dependencies-only

      - save_cache:
          key:    stack--{{ checksum "ghc.version" }}--{{ .Environment.CACHE_VERSION }}--{{ checksum "resolver.version" }}--{{ checksum "package.yaml" }}
          paths:  [~/.stack, ~/project/.stack-work]

      - run: stack build --test --no-run-tests

      - save_cache:
          key:    stack--{{ checksum "ghc.version" }}--{{ .Environment.CACHE_VERSION }}--{{ checksum "resolver.version" }}--{{ checksum "package.yaml" }}--{{ checksum "stack.yaml" }}
          paths:  [~/.stack, ~/project/.stack-work]

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Running unit tests
          command: stack test

      - run:
          name: Build the container
          command: ./scripts/container.sh build

      - deploy:
          name: Pushing container
          command: ./scripts/container.sh push
